language: php
cache: false

sudo: false

php:
  - 7.2
  - 7.3

before_script:
  - composer self-update
  - composer install

script:
  - ./vendor/bin/phpunit --disallow-test-output --coverage-clover ./clover.xml -c phpunit.dist.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./clover.xml
